language: node_js
node_js:
  - '8.12.0'
script:
  - npm build:test
  - npm test
  - npm run build
deploy:
  provider: npm
  email: shinken008@gmail.com
  skip_cleanup: true
  api_key:
    secure: 8MsGatnPbJXdXM+5bJsW00ughwIjjFecVF8rgfZUdBOjHcyAj6X3hDBQqiWh/OqlbBvoiRtShupgFz4PuDCE37gfiS4m8SxONFnqlORN6Kv3AaWcW1Uh7rCxBhUHTK2TSLrbZcyOy+yv0TwvlwHDBPsRJi/9cHQEeMFAzt8ydwgffVLjQd0OcxTwj6oP0x8C01xjc0hRMfszAJ3xblxhKKSfdvASEtd64tWrDllXf0clMY5PKcqYntW1rkBPS7Mn9I4YL/O9dzhNkKKP4k0iJqJvWkT1OnjcQ92s2GJZb9W/DLW/qzTNf3u485RVsn4QgWC6b6rrswKzC7/OK6rADu1Cw6V9K8FeI8Eb1mN+yD0YJP0M8kBB7XzSCYW8RXrxkZZLcjck8kMVG5IxfD93MYFUaQ8OhplSvthpRS3IGQ0J0divLXmDliu+juGnhe5z86TD68dLi0peVHGL3RfgJePIdcAjvAOnZzQUvWqcBi43fiRIEaAz2AHdLlZhuBUWZwT1/FJhY/vQUtJj5zXVuYRgoJ70mKQasXw9nInBRkkXrAL0gOBSdJpE8nUEYGlcssS/T39Bj4DbGSUgdjdf3seWY+5qWV89z+skiZZTlMa4n1ARlJy2ARWgaO8PWZ+CdoWmFbtIvB0YBqGclLHpl4SHGaZuTBwtGgf+vFqi0v8=
  on:
    tags: true
